pipeline {
    agent any
    
    tools {
        maven 'Maven_3.5.4'
    }
    
    environment {
        ROOT_DIR = 'rest-test'
    }


    stages {
    
	    stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                ''' 
            }
        }
        stage('Build') {
            steps {
            	    dir("${ROOT_DIR}") {
                        sh 'mvn -Dmaven.test.failure.ignore=true package test'
            	    }
            }
            post {
                success {
                    junit '**/target/surefire-reports/**/*.xml' 
                    jacoco(execPattern: '**/target/coverage-reports/jacoco-ut.exec')
                }
            }
        }
        stage('docker') {
            steps {
                echo 'Build docker image'
                script {
					def img = docker.build("rest-test-${env.BUILD_ID}", "rest-test")
            		img.run('-p 8181:8080 --name jenkins_int_test')
            	}
            }
        }
        stage('Integration-test') {
            steps {
                echo 'Run integration tests against the docker container'
            	    dir("${ROOT_DIR}") {
                        sh 'mvn verify -Dskip.unit.tests -Dtest.url=docker.host.internal:8181'
            	    //docker.container('jenkins_int_test').stop()
       				sh 'docker stop jenkins_int_test'	
            	    }
            }
        }

    }
}